config/routes.rb
Air::Application.routes.draw do

  root :to => 'flights#index'
  
  resources :reservations
  resources :users
  resources :flights
  resources :airports

  get "sessions/new", :as => :login_page
  post "sessions/create"
  delete "sessions/destroy"


end

app/models/airport.rb
class Airport < ActiveRecord::Base
end

app/models/flight.rb
class Flight < ActiveRecord::Base
  
  belongs_to :departure_airport, 
             :class_name => 'Airport', 
             :foreign_key => 'departure_airport_id'
  
  belongs_to :arrival_airport, 
             :class_name => 'Airport', 
             :foreign_key => 'arrival_airport_id'
  
  def duration
    distance / 6  # Assume we can go 6 miles per minute
  end
    
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  
  belongs_to :user
  belongs_to :flight
  
end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_secure_password

  has_many :reservations
  
  def miles
    total_miles = 0
    reservations.each do |reservation|
      total_miles = total_miles + reservation.flight.distance
    end
    total_miles
  end
  
end

app/controllers/airports_controller.rb
class AirportsController < ApplicationController
  
  def show
    @airport = Airport.find(params[:id])
  end
  
  def index
    if params[:zebra].present?
      @airports = Airport.where(["city LIKE ?", "%#{params[:zebra]}%"])
    else
      @airports = Airport.all
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  # GET /flights
  # GET /flights.json
  def index
    
    if params[:meal]
      @flights = Flight.where(["meal = ?", true])
    else
      @flights = Flight.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @flights }
    end
  end

  # GET /flights/1
  # GET /flights/1.json
  def show
    @flight = Flight.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @flight }
    end
  end

  # GET /flights/new
  # GET /flights/new.json
  def new
    @flight = Flight.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @flight }
    end
  end

  # GET /flights/1/edit
  def edit
    @flight = Flight.find(params[:id])
  end

  # POST /flights
  # POST /flights.json
  def create
    @flight = Flight.new(params[:flight])

    respond_to do |format|
      if @flight.save
        format.html { redirect_to @flight, :notice => 'Flight was successfully created.' }
        format.json { render :json => @flight, :status => :created, :location => @flight }
      else
        format.html { render :action => "new" }
        format.json { render :json => @flight.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /flights/1
  # PUT /flights/1.json
  def update
    @flight = Flight.find(params[:id])

    respond_to do |format|
      if @flight.update_attributes(params[:flight])
        format.html { redirect_to @flight, :notice => 'Flight was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @flight.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /flights/1
  # DELETE /flights/1.json
  def destroy
    @flight = Flight.find(params[:id])
    @flight.destroy

    respond_to do |format|
      format.html { redirect_to flights_url }
      format.json { head :ok }
    end
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  
  before_filter :require_user
  
  def require_user
    if session[:user_id] == nil
      redirect_to root_url, :notice => "No way!"
    end
  end
    
  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @reservations }
    end
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
    @user = User.find(session[:user_id])
    @reservation = @user.reservations.find(params[:id])
    
    if @reservation == nil
      redirect_to root_url, :notice => "Nice Try, Hacker!"
      return
    end
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @reservation }
    end
  end

  # GET /reservations/new
  # GET /reservations/new.json
  def new    
    @user = User.find(session[:user_id])
    @flight = Flight.find(params[:flight_id])
    @reservation = Reservation.new
    @reservation.user = @user
    @reservation.flight = @flight
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @reservation }
    end
  end

  # GET /reservations/1/edit
  def edit

  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(params[:reservation])
    @reservation.user = User.find(session[:user_id])
    
    respond_to do |format|
      if @reservation.save
        ReservationsMailer.send_confirmation(@reservation).deliver
        format.html { redirect_to root_url, :notice => 'Reservation was successfully created.' }
        format.json { render :json => @reservation, :status => :created, :location => @reservation }
      else
        format.html { render :action => "new" }
        format.json { render :json => @reservation.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /reservations/1
  # PUT /reservations/1.json
  def update
    @reservation = Reservation.find(params[:id])

    respond_to do |format|
      if @reservation.update_attributes(params[:reservation])
        format.html { redirect_to @reservation, :notice => 'Reservation was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @reservation.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    user = User.find(session[:user_id])
    @reservation = user.reservations.find(params[:id])
    @reservation.destroy
    
    respond_to do |format|
      format.html { redirect_to user_url(user), :notice => "Your reservation to #{@reservation.flight.arrival_airport.city} has been cancelled." }
      format.json { head :ok }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_url(user), :notice => "Welcome back!"
    else
      flash[:notice] = "Please try again."
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to root_url, :notice => "You have signed out."
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    
    if @user.save
      flash[:notice] = "Thanks for signing up!"
      session[:user_id] = @user.id
      redirect_to root_url
    else
      flash[:notice] = "No way!"
      render :new
    end
  end
  
  def show
    @user = User.find(session[:user_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def logged_in?
    session[:user_id]
  end
  
  def current_user
    if session[:user_id]
      return User.find(session[:user_id])
    end
  end
  
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/airports/_airport.html.erb
<p><%= airport.code %> - <%= airport.city %></p>

app/views/airports/index.html.erb
<h1>Airports We Serve</h1>

<%= form_tag airports_url, :method => :get do %>
<p>Search by City: <%= text_field_tag :zebra, params[:zebra] %></p>
<%= submit_tag "Filter Now" %>
<% end %>

<%= render @airports %>

app/views/airports/show.html.erb
<h1><%= @airport.code %> - <%= @airport.city %></h1>

<%= image_tag "#{@airport.code.downcase}.gif" %>

app/views/flights/_flight.html.erb
<tr>
  <td><%= flight.number %></td>
  <td><%= flight.departs_at.localtime.strftime("%I:%m %p") %></td>
  <td><%= link_to flight.departure_airport.code, airport_url(flight.departure_airport) %></td>
  <td><%= flight.arrival_airport.code %></td>
  <td><%= flight.distance %> miles</td>
  <td><%= flight.meal? ? "Yes" : "No"%></td>
  <td class="book"><%= link_to "Book Now", new_reservation_url(:flight_id => flight.id) if logged_in? %></td>
</tr>

app/views/flights/_form.html.erb
<%= form_for(@flight) do |f| %>
  <% if @flight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@flight.errors.count, "error") %> prohibited this flight from being saved:</h2>

      <ul>
      <% @flight.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br />
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label :departs_at %><br />
    <%= f.time_select :departs_at %>
  </div>
  <div class="field">
    <%= f.label :departure_airport_id %><br />
    <%= f.collection_select :departure_airport_id, Airport.all, :id, :city %>
  </div>
  <div class="field">
    <%= f.label :arrival_airport_id %><br />
    <%= f.collection_select :arrival_airport_id, Airport.all, :id, :city %>
  </div>
  <div class="field">
    <%= f.label :distance %><br />
    <%= f.number_field :distance %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/flights/edit.html.erb
<h1>Editing flight</h1>

<%= render 'form' %>

<%= link_to 'Show', @flight %> |
<%= link_to 'Back', flights_path %>

app/views/flights/index.html.erb
<aside>
  <div class="box">
    <h1>Flight Search</h1>
    <%= form_tag flights_url, :method => :get do %>
      <ul>
        <li class="text">
          <%= label_tag :from, "From"%>
          <%= text_field_tag :from %>
        </li>
        <li class="text">
          <%= label_tag :to, "To"%>
          <%= text_field_tag :to %>
        </li>
      
        <li class="check">
          <strong>Stops</strong>
          <%= check_box_tag :nonstop %><%= label_tag :nonstop, "Nonstop" %>
          <%= check_box_tag :onestop %><%= label_tag :onestop, "1 Stop" %>
          <%= check_box_tag :plusstop %><%= label_tag :plusstop, "2+ Stops", :class  => "last" %>
        </li>
        <li class="check">
          <strong>Meal Service</strong>
          <%= check_box_tag :meal %><%= label_tag :meal, "Yes" %>
          <%= check_box_tag :nomeal %><%= label_tag :nomeal, "No" %>
        </li>
        <li class="submit">
          <%= submit_tag "Search" %>
        </li>
        <li class="hint">
          (<%= link_to "View All Available Airports", airports_url %>)
        </li>
      </ul>
    <% end %>
  </div>
</aside>

<section>
  <table>
    <tr>
      <th>Number</th>
      <th>Time</th>
      <th>Departure</th>
      <th>Arrival</th>
      <th>Distance</th>
      <th>Meal Service</th>
      <th></th>
    </tr>
    <%= render @flights %>
  </table>
</section>

<div class="clear"></div>

app/views/flights/new.html.erb
<h1>New flight</h1>

<%= render 'form' %>

<%= link_to 'Back', flights_path %>

app/views/flights/show.html.erb
<p>
  <b>Number:</b>
  <%= @flight.number %>
</p>

<p>
  <b>Departs at:</b>
  <%= @flight.departs_at %>
</p>

<p>
  <b>Departure airport:</b>
  <%= @flight.departure_airport_id %>
</p>

<p>
  <b>Arrival airport:</b>
  <%= @flight.arrival_airport_id %>
</p>

<p>
  <b>Distance:</b>
  <%= @flight.distance %>
</p>


<%= link_to 'Edit', edit_flight_path(@flight) %> |
<%= link_to 'Back', flights_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AcademyAir</title>
  <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="container">
    
    <header>
      <h1><%= link_to root_url do %>Academy<span>Air</span><% end %></h1>
      <% if logged_in? %>
        <ul>
          <li><%= link_to "Sign Out", sessions_destroy_url, :method => :delete %></li>
          <li class="btn"><%= link_to "My Account", user_url(current_user) %></li>
        </ul>
        <p>Hello, <%= current_user.first_name %> <%= current_user.last_name %>!</p>
      <% else %>
        <ul>
          <li><%= link_to "Sign In", login_page_url %></li>
          <li class="btn"><%= link_to "Sign Up", new_user_url %></li>
        </ul>
      <% end %>
      <div class="clear"></div>
    </header>
    
    <nav>
      <ul>
        <li><a href="#" title="Reservations">Reservations</a></li>
        <li><a href="#" title="Deals and Specials">Deals &amp; Specials</a></li>
        <li><a href="#" title="Rewards">Rewards</a></li>
        <li><a href="#" title="Travel Information">Travel Information</a></li>
        <li><a href="#" title="About Us">About Us</a></li>
        <li><a href="#" title="Contact Us">Contact Us</a></li>
      </ul>
    </nav>
    
    <% if flash[:notice] %>
      <p id="notice"><%= flash[:notice] %></p>
    <% end %>
    
    <%= yield %>
    
  </div>
  
</body>
</html>

app/views/reservations/_form.html.erb
<%= form_for(@reservation) do |f| %>
  <% if @reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% @reservation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<p><strong>For: </strong><%= @user.first_name %> <%= @user.last_name %></p>

<p>Flight #<%= @flight.number %></p>
<p>Departs <%= @flight.departure_airport.code %>  <%= @flight.departure_airport.city %> at <%= @flight.departs_at.strftime("%I:%M %p") %></p>
<p>Arrives <%= @flight.arrival_airport.code %>  <%= @flight.arrival_airport.city %> at <%= (@flight.departs_at + @flight.duration*60).strftime("%I:%M %p") %></p>
  
  <%= f.hidden_field :flight_id %>
  
  <div class="field">
    <%= f.label :travels_on, "What day to you want to leave?" %><br />
    <%= f.date_select :travels_on %>
  </div>
  <div class="field">
    <%= f.label :card_number %><br />
    <%= f.text_field :card_number %>
  </div>
  <div class="actions">
    <%= f.submit %> or <%= link_to "Cancel", :back %>
  </div>
<% end %>

app/views/reservations/edit.html.erb
<h1>Editing reservation</h1>

<%= render 'form' %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<h1>Listing reservations</h1>

<table>
  <tr>
    <th>User</th>
    <th>Flight</th>
    <th>Travels on</th>
    <th>Card number</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @reservations.each do |reservation| %>
  <tr>
    <td><%= reservation.user_id %></td>
    <td><%= reservation.flight_id %></td>
    <td><%= reservation.travels_on %></td>
    <td><%= reservation.card_number %></td>
    <td><%= link_to 'Show', reservation %></td>
    <td><%= link_to 'Edit', edit_reservation_path(reservation) %></td>
    <td><%= link_to 'Destroy', reservation, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Reservation', new_reservation_path %>

app/views/reservations/new.html.erb
<h1>New reservation</h1>

<%= render 'form' %>

app/views/reservations/show.html.erb
<h1>Reservation Details</h1>

<p><%= button_to "Cancel This Reservation", reservation_url(@reservation), :method => :delete, :confirm => "Are you really sure?" %> </p>

<h2>Who's Flying</h2>

<%= render @user %>

<h2>Flight Details</h2>
<p>Flight #<%= @reservation.flight.number %></p>
<p>Time: <%= @reservation.flight.departs_at.localtime.strftime("%I:%M %p") %></p>
<p>Departs: <%= @reservation.flight.departure_airport.city %></p>
<p>Arrives: <%= @reservation.flight.arrival_airport.city %></p>

<p>
  <b>Travels on:</b>
  <%= @reservation.travels_on %>
</p>

<p>
  <b>Card number:</b>
  <%= @reservation.card_number %>
</p>

app/views/users/_user.html.erb
<p><%= @user.first_name %> <%= @user.last_name %></p>
<p><%= @user.street %></p>
<p><%= @user.city %>, <%= @user.state %> <%= @user.zip %></p>

app/views/users/new.html.erb
<article>
  <h1>Sign Up</h1>
  <%= form_for @user do |form| %>
    <ul>
      <li class="text">
        <label for="user_first_name">First Name</label>
        <%= form.text_field :first_name %>
      </li>
      <li class="text">
        <label for="user_last_name">Last Name</label>
        <%= form.text_field :last_name %>
      </li>
      <li class="text">
        <label for="user_email">Email</label>
        <%= form.text_field :email %>
      </li>
      <li class="text">
        <label for="user_password">Password</label>
        <%= form.password_field :password %>
      </li>
      <li class="text">
        <label for="user_password_confirmation">Confirm Password</label>
        <%= form.password_field :password_confirmation %>
      </li>
      <li class="submit">
        <%= form.submit "Create Account" %>
      </li>
    </ul>
  <% end %>
</article>

app/views/users/show.html.erb
<article>
<h1>My Account</h1>
<p><strong>Total Miles Earned</strong>: <%= @user.miles %> Miles</p>

<h2>Personal Information</h2>
<p><%= @user.first_name %> <%= @user.last_name %><br />
<%= @user.street %><br />
<%= @user.city %>, <%= @user.state %> <%= @user.zip %></p>

<h2>My Reservations</h2>
<% @user.reservations.each do |reservation| %>
  <% if reservation.flight %>
    <p>
      <%= link_to "View Details", reservation_url(reservation) %> <%= reservation.flight.departure_airport.code %> to <%= reservation.flight.arrival_airport.code %>
      on <%= reservation.travels_on %> (<%= reservation.flight.distance %> miles)
    </p>
  <% end %>
<% end %>
</article>